Repository 1laurelverma/DSA-Solutions, pull requests merged in 2022-10, with the labels that each got.

#1 47. permutations-ii
  47.permutations-ii.cpp
Labels: hactoberfest-accepted

#2 added 56.merge-intervals leetcode
  56. Merge Intervals.cpp
Labels: hactoberfest-accepted, hactoberfest

#3 added 43. Multiply Strings leetcode
  43. Multiply Strings.cpp
Labels: hactoberfest-accepted, hactoberfest, hactoberfest2022

#5 Create Print Number Entered by User.cpp
  Print Number Entered by User.cpp
Labels: hactoberfest-accepted

#11 Create GCD using for loop.cpp
  GCD using for loop.cpp
Labels: hactoberfest-accepted

#8 Create Program to Add Two Integers.cpp
  Program to Add Two Integers.cpp
Labels: hactoberfest-accepted

#9 Create sum_triangle.cpp
  sum_triangle.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#10 Create Swap Numbers.cpp
  Swap Numbers.cpp
Labels: hactoberfest-accepted

#12 Create Find LCM.cpp
  Find LCM.cpp
Labels: hactoberfest-accepted

#14 Enter name and print 'Apka naam' + name
  name.cpp
Labels: hactoberfest-accepted

#13 Create Reverse an Integer.cpp
  Reverse an Integer.cpp
Labels: hactoberfest-accepted

#15 XOR Encryption by Shifting Plaintext
  XOR Encryption by Shifting Plaintext.cpp
Labels: hactoberfest-accepted

#18 Changes idk kya
  EqPairCodeChef.cpp
Labels: hactoberfest-accepted

#16 Create Find_GCD_Efficient_Approach.cpp
  Find_GCD_Efficient_Approach.cpp
Labels: hactoberfest-accepted

#19 Add Banker's Algorithm
  BANKERS-ALGO.cpp
Labels: hactoberfest-accepted

#20 towe of honoi using recursion
  tower_of_hanoi_recursion.cpp
Labels: hactoberfest-accepted

#21 Solution of SUBARRAY from CodeChef
  SubArrayCodeChef.cpp
Labels: hactoberfest-accepted

#22 Solution of SPEEDTEST from CodeChef
  SpeedTestCodeChef.cpp
Labels: hactoberfest-accepted

#30 Sanketr113
  Cyclic_Sort.cpp
  Merge-Sort.cpp
Labels: hactoberfest-accepted

#29 Create ManagementSystem.cpp
  ManagementSystem.cpp
  Remove AllOccurrencesofaSubstring.cpp
  Student.cpp
Labels: hactoberfest-accepted

#28 Create Search in Rotated Sorted Array.cpp
  Search in Rotated Sorted Array.cpp
Labels: hactoberfest-accepted

#26 Create largest-sum-contiguous-subarray.cpp
  largest-sum-contiguous-subarray.cpp
Labels: hactoberfest-accepted

#25 add cpp code to find the first missing positive integer in an array
  first_missing_positive.cpp
Labels: hactoberfest-accepted

#27 Create 34. Find First and Last Position of Element in Sorted Array.cpp
  34. Find First and Last Position of Element in Sorted Array.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#31 Create Insertion Sort
  Insertion Sort
Labels: hactoberfest-accepted, hactoberfest2022

#24 Create quotient_and_remainder.cpp
  quotient_and_remainder.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#7 upload new file algorithms
  linier-search.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#32 Infix to postfix program
  infix to postfix.cpp
Labels: hactoberfest-accepted, hactoberfest, hactoberfest2022

#35 Add files via upload
  merge sort.cpp
Labels: hactoberfest-accepted

#34 LongestPalindromicSubstring
  LongestPalindromicSubstring.cpp
Labels: hactoberfest-accepted

#36 Insertion and deletion in queue
  insertion and deletion in Queue.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#37 Quick Sort
  quick sort.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#38 Added bubble_sort.cpp
  bubble_sort.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#43 Brian Kernighan’s algorithm
  Brian_Kernighan’s_algorithm.cpp
Labels: hactoberfest-accepted

#41 Create First and last position in an array
  First and last position in an array
Labels: hactoberfest-accepted

#42 Create Quick_Sort.cpp
  Quick_Sort.cpp
Labels: hactoberfest-accepted

#40 Create removeNthNodeFromEnd.c
  removeNthNodeFromEnd.c
Labels: hactoberfest-accepted

#39 Create PeakIndexinaMountainArray.cpp
  PeakIndexinaMountainArray.cpp
Labels: hactoberfest-accepted

#44 Create Level Order Binary Tree Traversal
  Level Order Binary Tree Traversal
Labels: hactoberfest-accepted, hactoberfest2022

#45 Create Reverse_tree_path.cpp
  Reverse_tree_path.cpp
Labels: hactoberfest-accepted

#48 Flatten-A-Linked-List
  46.Flatten-A-Linked-List.cpp
Labels: hactoberfest-accepted

#49 added
  56.Remove-Duplicates-from-Sorted-Array.cpp
Labels: hactoberfest-accepted

#51 Added the code for preorder traversal of a Binary Tree.
  preorder_traversal.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#52 Add Doubly Linked List
  doubly_linked_list.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#56 Add Unique Num of Occurrences
  1207-unique-number-of-occurrences.cpp
Labels: hactoberfest-accepted

#50 Sudokusolver.cpp
  Sudokusolver.cpp
Labels: hactoberfest-accepted

#57 445.add-two-numbers-ii.cpp
  445.add-two-numbers-ii.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#58 503.next-greater-element-ii.cpp
  503.next-greater-element-ii.cpp
Labels: hactoberfest-accepted

#59 square root of a number in c++
  69.sqrtx.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#60 solve N QUEENS problem
  N_Queens.cpp
Labels: hactoberfest-accepted

#61 create 3Sum_closest
  3Sum_Closest.cpp
Labels: hactoberfest-accepted

#64 Create LCS_dp.cpp
  LCS_dp.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#63 Create cutting_a_rod.cpp
  cutting_a_rod.cpp
Labels: hactoberfest-accepted

#62 Karatsuba algorithm
  Karatsuba algorithm.cpp
Labels: hactoberfest-accepted

#65 Create Tiling_problem.cpp
  Tiling_problem.cpp
Labels: hactoberfest-accepted

#75 Added Three Dice Problem
  threedice.cpp
Labels: hactoberfest-accepted

#77 Added Word Search
  236. Lowest Common Ancestor of a Binary Tree.cpp
  Word Search.cpp
Labels: hactoberfest-accepted

#66 Create pyramid_using_*.cpp
  pyramid_using_*.cpp
Labels: hactoberfest-accepted

#67 Create_Check_Number_Type_with_if...else_if_else.js
  Check_Number_Type_with_if...else_if_else.js
Labels: hactoberfest-accepted

#68 AVL trees in C
  AVL_trees.c
Labels: hactoberfest-accepted

#69 Create PalindromeCheck.java
  PalindromeCheck.java
Labels: hactoberfest-accepted

#70 Create ArmstrongNumberCheck.java
  ArmstrongNumberCheck.java
Labels: hactoberfest-accepted

#74 938. Range Sum of BST
  Range_Sum_of_BST.c
Labels: hactoberfest-accepted

#71 Create Pyramid_Using_Stars.java
  Pyramid_Using_Stars.java
Labels: hactoberfest-accepted

#72 Practice
  HeapSort.cpp
Labels: hactoberfest-accepted

#76 Middle of Linked List.cpp
  Middle of Linked List.cpp
Labels: hactoberfest-accepted

#78 264 leetcode
  264-Ugly-Number-II.cpp
Labels: hactoberfest-accepted

#79 DES algorithm in C++
  data_encyption_standard.cpp
Labels: hactoberfest-accepted

#80 counting_sort
  264-Ugly-Number-II.cpp
  445.add-two-numbers-ii.cpp
  46.Flatten-A-Linked-List.cpp
  47.permutations-ii.cpp
  503.next-greater-element-ii.cpp
  56.Remove-Duplicates-from-Sorted-Array.cpp
  69.sqrtx.cpp
  AVL_trees.c
  EqPairCodeChef.cpp
  Karatsuba algorithm.cpp
  N_Queens.cpp
  Sieve of Eratosthenes.java
  SpeedTestCodeChef.cpp
  SubArrayCodeChef.cpp
  XOR Encryption by Shifting Plaintext.cpp
  counting.c
  infix to postfix.cpp
  insertion and deletion in Queue.cpp
  merge sort.cpp
  name.cpp
  pyramid_using_*.cpp
  quick sort.cpp
  tower_of_hanoi_recursion.cpp
Labels: hactoberfest-accepted

#82 insertion_vector.cpp
  insertion_vector.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#81 deletion_vector.cpp
  deletion_vector.cpp
Labels: hactoberfest-accepted
